### ISSUE TITLE
Faucet 503 response timeout

### ISSUE THREAD

**Issue by anhcao142** [StardustCollective/dag4.js-wallet-demo#1]
Hi, I try to tap the faucet by directly running this URL: https://us-central1-dag-faucet.cloudfunctions.net/main/api/v1/faucet/ceres/DAG76rSmtsSiCyePKjPLNp9ExFWacS2MJqEZL5w3?amount=1 but get 503 - Response timeout error

**Comment by ffox77** [comment]
**ceres** is our testnet that is currently being prepared for a new release. In the mean time you can get DAG from main net faucet. Reach out to @doc_holliday87 on telegram for the link.

**Comment by anhcao142** [comment]
Thanks @ffox77, I think this is resolved
